[pytest]
testpaths = testes
pythonpath = .
addopts =
    -v
    --tb=short
    --no-header
    --strict-markers
    -p no:cacheprovider

markers =
    integration: testes que dependem de banco de dados ou rede (deselect with '-m "not integration"')
    slow: testes lentos (deselect with '-m "not slow"')
